[[session]]
name = "default"

[[session]]
name = "admin"
startup_command = "ssh admin -t 'tmux a'"

[[session]]
name = "nix-01"
startup_command = "ssh -q nix-01 -t 'tmux a'"

[[session]]
name = "nix-03"
startup_command = "ssh -q nix-03 -L 10350:localhost:10350 -L 3000:localhost:3000  -t 'tmux a'"


